---
galaxy_info:
  author: Andrew Rothstein
  description: installs kubernetes helm
  company: BlackRock
  license:
    - MIT
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - jessie
    - name: Alpine
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - development
    - paas
    - k8s
    - helm

dependencies:
  - src: andrewrothstein.unarchive-deps
    version: v1.0.9
